apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-simple-2
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.29.0"
    tekton.dev/categories: Git
    tekton.dev/tags: git
    tekton.dev/displayName: "simple 2"
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  description: >-
    These Tasks are Git tasks to work with repositories used by other tasks
    in your Pipeline.
  steps:
    - name: echo
      image: alpine
      script: |
        #!/bin/sh
        echo "Hello World git-simple-2 V2 updated"   
